### PR TITLE
NewFileFilter and button color

### PR DESCRIPTION
**Pull request by Guiorgy**
the new File Filter didn't behave as intended, also forgot to set the buttons text color (only did it to the drawables)

```
if (!files.remove(dirFile)) {
     files.add(dirFile);
}
```
remove returns true if item was removed and false if not, in other words, if a File was selected twice it has been deselected, hence we remove it from the list.

PS. just check the FileUtils, and FileChooser changes ignore everything else XD

### CODE REVIEW

**Comment by Guiorgy** [comment]
also noticed that, when you go to a new directory (or go back) it doesn't reset your scroll position.

**Comment by hedzr** [comment]
ok, i get it.

**Comment by Guiorgy** [comment]
@hedzr , so I cannot make a pull request because they "are entirely different commit histories."

anyways check my 'empty' branch hotfixes commit. what I did was:
* fixed the NewFileFilter.
* fixed the button text colors.
* fixed deleting files in select multiple mode. (!most important)
* made the list scroll to top when changing directories.

**Comment by hedzr** [comment]
my fault to reformatted codes in one of commit. i'm checking and working there.

**Pull request closed without merging**
