### PR TITLE
rework of the Dpad patch

### PR DESCRIPTION
**Pull request by Guiorgy**

### CODE REVIEW

**Comment by hedzr** [comment]
i'll review all later and tomorrow. thanks a lot.

**Comment by Guiorgy** [comment]
added the left and right keys (back and itemClick)

**Comment by Guiorgy** [comment]
'.. SDCard Storage' doesn't seem to show on my emulator:
sdcard

**Comment by hedzr** [comment]
@Guiorgy here are the codes to get inner(primary) storage and sdcard pathes:
```java
String removableRoot = FileUtil.getStoragePath(_context, true);
String primaryRoot = FileUtil.getStoragePath(_context, false);
```
would u please trace it on your envir. or dump some information?

**Comment by Guiorgy** [comment]
fac85ee... shoud I close this pull request?

**Pull request closed without merging**
