### PR TITLE
X1.2.0 androidx

### PR DESCRIPTION
**Pull request by Buggaboo**
Changes
* Changed imports to androidx (jetpack)
* Changed android.app.AlertDialog to androidx's to support theme/styles e.g. material design
* Upgraded gradle and android plugins

### CODE REVIEW

**Comment by hedzr** [comment]
Nice! I do appreciate the work.

x1.2.0 had been held because these reasons:
1. v1.1.x can work in an androidx project. It seems, several days ago i'd seen/checked.
2. **x1.2.0 has many commits behind of the master/devel branch**.
3. ~~It need more time to delivery another jcenter library and maintain a double-branches series~~.
4. I have no plenty of time to write new codes for x1.2.0, and others.

The second pt should be noted here. Therefore, if you completed the works from x1.2.0, it could be not a good start. I'm sure that's **my** bad. I should have advanced it (x1.2.0) with master/devel branch, that ought to be a better start.

So @Buggaboo, would you like transform to androidx as `new-x1.2.0` starting with our newest `devel` branch? If so, I'll make the branch for your new PR, and, the `x1.2.0` can be archived from then on.

**Comment by Buggaboo** [comment]
Sorry, I don't think I understand you completely, you're asking if I want my PR branch to replace _x1.2.0_?

I can also apply the same changes to the master branch if you like. I require a new release with the _androidx_ and _androidx.appcompat.app.AlertDialog_ changes.

**Comment by hedzr** [comment]
well my ado.
shortly, our `x1.2.0` is too older than devel. it's not worthy to merge your work. so we can make a new branch named as `new-x1.2.0` based on devel, could you please migrate your changes on this new one?

**Comment by Buggaboo** [comment]
Ah, I understand, yes I will send a new PR based on this new ```new-x1.2.0``` branch.

**Comment by hedzr** [comment]
💃 
There is it: `new-x1.2.0`.

**Comment by Guiorgy** [comment]
seems we can close this PR as there's #67 instead. Also, @hedzr, how about we remove the old 1.2.0 branch to prevent future confusion? (if theres anything there, we can keep it localy for now)

**Pull request closed without merging**
