### PR TITLE
update demo app, and 2 small bug fixes

### PR DESCRIPTION
**Pull request by Guiorgy**
1. Sd card showing even when there is none.
2. _deleteModeIndicator being null and throwing NullPointerException

### CODE REVIEW

**Comment by Guiorgy** [comment]
Just jound those...

**Comment by Guiorgy** [comment]
ahh. Didn't mean to commit the demo app here -_-.
But please check it out whyle at it?

**Comment by hedzr** [comment]
善哉

**Comment by Guiorgy** [comment]
1 trouble though, the app now needs to be translated again. I can only do Russian so...

**Comment by hedzr** [comment]
I mean that's nice, but it will be merged at tomorow morning (+0800). Away from table.

**Comment by Guiorgy** [comment]
Oleksandr Firsov on Play Store reported NullPointerException in onItemLongClick. I believe this was the problem. Should be fixed now!

**Comment by hedzr** [comment]
It's a long overdue to abandon my ugly demo codes.
They have a kind and beautiful look now.

**Pull request merged**
