### PR TITLE
small tweaks

### PR DESCRIPTION
**Pull request by Guiorgy**
- fileChooserNewFolderWidthWeight float range changed from 0-100 to 0-1, and default value from 55.56 to 0.56
- moved permission checking into it's own method and simplified show() method
- prevent options view from showing until it's ready on api > 21
- fixed newFolder view on api < 21

### CODE REVIEW

**Comment by hedzr** [comment]
I had to re-merged and push the codes because i'm lazy and do working on master. my bad. so i'd kept  on the `devel` now.
The codes on master has been checked. And, there are some new changes:
1. about dlg skeleton (i'm working).
2. extract some codes to the another java file, see also `keyListener.java` and `defBackPressed.java`
3. extract two string as const values.
There are no more changes whatever you are doing. Thx!

One more thing, i'm thinking about `setupOnShowListener()`, should we do split it to a single java file?

**Comment by Guiorgy** [comment]
I'll be commiting to **`devel`** in the future then.
as for `setupOnShowListener()`, ChooserDialog fields are used and changed there. If we move it, then we will have to either provide package private getters-setters, or make field themselvs package private. if you think that it's worth it, then let me know and I can do it.
edit: actually you already made some fields package private huh.
edit2: #59 you can look through it, if this is what you wanted then you can merge it.

**Comment by hedzr** [comment]
sorry i didn't make it clear: you could work same as before. i'll switch to devel instead of master.
yes, i'd seen and i'll do it tonight

**Comment by Guiorgy** [comment]
ah, I see. If it makes it easier, you could make a branch for me as well?

**Comment by hedzr** [comment]
if you pull the repo directly too, you should make another working branch and merge it to master, because we both are online. In this case, you can do that yourself (make any branch on this repo.)
if you make a PR and merge it, no changes are needed.

**Comment by hedzr** [comment]
i guess that you could push many branches onto this repo, but i'm not sure.

**Comment by Guiorgy** [comment]
gotcha

**Pull request merged**
