### PR TITLE
(#45) display file path

### PR DESCRIPTION
**Pull request by Guiorgy**
an alternative solution to showing current directory in the title. a TextView at the top of the list with the current path. If whole path doesn't fit, then it gets trimmed from the left. This will not remove _folowDir, but rather give an alternative, as it doesn't require the title to be enabled. Oh, and I also updated android-maven-gradle-plugin: 2.0 -> 2.1 and kotlin-gradle-plugin: 1.3.11 -> 1.3.21.

heres a demo:
demo

### CODE REVIEW

**Comment by hedzr** [comment]
nice job!

**Comment by hedzr** [comment]
i will update readme with the gif link tomorrow.

**Comment by Guiorgy** [comment]
In the first commit swap lines 1021 and 1022 please :p

Those 2:
```java
if (i == -1) break;
i = path.indexOf("/", i + 1);
```
need to be swapped

**Comment by hedzr** [comment]
should i swap these two lines?
```java
                if (i == -1) break;
                i = path.indexOf("/", i + 1);
```

PS:
1. what do you think of the `_path` renamed to `_pathView`?

---

I added customizePathView(callback), renamed to `_pathView` because `_path` is a confusing name, and reformatted the codes, be kindly informed pls.

**Comment by Guiorgy** [comment]
@hedzr 
1. if (i == -1) break; is just incase there are no '/' in path (somehow), which would throw OutOfBoundException, though I have yet to have that problem...
2. Honestly, my naming scense is the worst. :) feel free to rename anything anyway you prefere.
3. I like the idea of the callback.
4. I just realised, but TextView.setPadding(l,t,r,b) takes in px. We should use UiUtil.dip2px(dip) there!

**Comment by hedzr** [comment]
Got it. I appreciate for your consideration/understanding.
About last point, i'd remembered to find another time to do that.

**Comment by Guiorgy** [comment]
By the way, @hedzr, most demo apps usually have toggleable settings to let the user test more stuff. like this:
this
example from [calcdialog](https://github.com/maltaisn/calcdialoglib).
What do you think about trying the same?

**Comment by hedzr** [comment]
Good idea but need a bit time, I think it could be planned soon because more and more properties done.

**Comment by Guiorgy** [comment]
@hedzr, I can give it a try, if you don't mind that is?

**Comment by hedzr** [comment]
It was my pleasure!

**Comment by Guiorgy** [comment]
@hedzr, looking at ChooserDiag:
```java
    public ChooserDialog titleFollowsDir(boolean followDir) {
        _followDir = followDir;
        return this;
    }

    public ChooserDialog followDir(boolean followDir) {
        _followDir = followDir;
        return this;
    }
```
those 2 do the same. 1 is redundant.

**Comment by hedzr** [comment]
yes, 2nd (`followDir`) is redundant, should be removed.

**Pull request merged**
